queue:
  name: Default
  
steps:
- task: BatchScript@1
  inputs:
    filename: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Enterprise\\Common7\\Tools\\VsDevCmd.bat"
    arguments: -no_logo
    modifyEnvironment: true
  displayName: Setup Environment Variables
    

- powershell: |
    dotnet test .\vsts-reporter\vsts-reporter.csproj
  displayName: Build
  env:
    VSTS_ACCESS_TOKEN: $(System.AccessToken)
